In [21]:
#Hi, I'll be showing this to predict NBA games. Our training dataset uses games from 2015 to 2022.
import pandas as pd
df = pd.read_csv("/kaggle/input/nbagameinfo/nba_games (1).csv", index_col=0)
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,50.0,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,20.0,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,28.6,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,16.8,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
17768,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,25.0,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True
17769,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,25.6,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False
17770,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
17771,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

In [22]:
df = df.sort_values("date")
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
16086,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
16904,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
16905,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
16087,240.0,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
1225,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,240.0,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
11533,240.0,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
11532,240.0,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
7477,240.0,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
7476,240.0,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [23]:
df = df.reset_index(drop=True)

df.drop(["mp.1","mp_opp.1", "index_opp"],axis = 1,inplace = True)

In [24]:
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

#Add a "target" or "predictions" column that has values of if the game
#that was played previously was won or lost
df = df.groupby("team",group_keys=False).apply(add_target)

#Example for Los Angeles Lakers
df[df["team"] == "LAL"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
13,240.0,35.0,90.0,0.389,9.0,34.0,0.265,32.0,35.0,0.914,...,31.3,206.0,119.0,MIN,112,0,2016,2015-10-28,False,False
56,240.0,41.0,89.0,0.461,11.0,34.0,0.324,21.0,27.0,0.778,...,33.3,200.0,112.0,SAC,132,1,2016,2015-10-30,False,False
76,240.0,31.0,85.0,0.365,10.0,34.0,0.294,21.0,28.0,0.750,...,24.0,155.0,105.0,DAL,103,0,2016,2015-11-01,False,False
116,240.0,36.0,86.0,0.419,6.0,26.0,0.231,31.0,38.0,0.816,...,27.5,193.0,115.0,DEN,120,0,2016,2015-11-03,False,True
152,240.0,33.0,78.0,0.423,7.0,23.0,0.304,31.0,40.0,0.775,...,27.2,116.0,109.0,BRK,98,1,2016,2015-11-06,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17468,240.0,49.0,92.0,0.533,6.0,20.0,0.300,14.0,21.0,0.667,...,46.1,201.0,121.0,DEN,129,0,2022,2022-04-03,False,False
17486,240.0,39.0,86.0,0.453,9.0,29.0,0.310,23.0,30.0,0.767,...,37.5,155.0,111.0,PHO,121,1,2022,2022-04-05,False,False
17525,240.0,37.0,83.0,0.446,9.0,32.0,0.281,29.0,38.0,0.763,...,31.6,300.0,114.0,GSW,128,1,2022,2022-04-07,False,True
17544,240.0,41.0,82.0,0.500,9.0,31.0,0.290,29.0,39.0,0.744,...,31.6,132.0,125.0,OKC,101,0,2022,2022-04-08,True,True
17581,265.0,44.0,94.0,0.468,16.0,43.0,0.372,42.0,47.0,0.894,...,34.7,159.0,138.0,DEN,141,1,2022,2022-04-10,True,NaN

In [25]:
#Assign Non-Null Values in Target to 2
df["target"][pd.isnull(df["target"])] = 2
df["target"] = df["target"].astype(int, errors="ignore")

nulls = pd.isnull(df)
nulls = nulls.sum()
nulls = nulls[nulls > 0]

valid_columns = df.columns[~df.columns.isin(nulls.index)]
df = df[valid_columns].copy()
df

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

In [26]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.7/site-packages (1.0.2)
Requirement already satisfied: joblib>=0.11 in /opt/conda/lib/python3.7/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: numpy>=1.14.6 in /opt/conda/lib/python3.7/site-packages (from scikit-learn) (1.21.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: scipy>=1.1.0 in /opt/conda/lib/python3.7/site-packages (from scikit-learn) (1.7.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [27]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import LogisticRegressionCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#Use Ridge Regression to weight features
rr = RidgeClassifier(alpha = 0.05)

#Using a Time Series to create the splits, which means that our future predictions consider historical data
split = TimeSeriesSplit(n_splits = 8)

sfs = SequentialFeatureSelector(rr, n_features_to_select = 20, direction = "forward", cv = split)

#Remove Non-Numerical Columns
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [29]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

#Scale the columns so all values fall between 0 and 1. This also makes it better for Ridge Regression
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [30]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=8, test_size=None),
                          estimator=RidgeClassifier(alpha=0.05),
                          n_features_to_select=20)

In [31]:
#These are the list of predictors that are deemed important after fitting

predictors = list(selected_columns[sfs.get_support()])
print(predictors)

['mp', 'usg%', 'pts_max', '+/-_max', 'trb%_max', 'mp_opp', '3p%_opp', 'ft%_opp', 'orb_opp', 'blk_opp', 'pts_opp', 'usg%_opp', 'ft_max_opp', 'ft%_max_opp', 'stl_max_opp', '3par_max_opp', 'ast%_max_opp', 'stl%_max_opp', 'tov%_max_opp', 'total_opp']

In [32]:
#We'll define this function to predict the outcomes for the current season
#given information from previous seasons.
#Then we append these results onto 1 dataframe.

def backtest(data,model, predictors, start = 2):
    all_predictions = [    ]
    seasons = [2016,2017,2018,2019,2020,2021,2022]
    for i in range(start,len(seasons)):
        train = data[data["season"] < seasons[i]]
        test = data[data["season"] == seasons[i]]
        model.fit(train[predictors], train["target"])
        preds =  pd.Series(model.predict(test[predictors]), index = test.index)
        combined = pd.concat([test["target"], preds], axis = 1)
        combined.columns = ["actual", "prediction"]
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [33]:
#Testing process of our first model
predictions = backtest(df,rr,predictors)

correct = 0
for ind in predictions[predictions["actual"] != 2].index:
    if(predictions['actual'][ind] == predictions['prediction'][ind]):
        correct = correct + 1

#Print the percentage of games that our model correctly predicted
#We see that this result is only 54.5%, which is considerably worse
#than the accuracy when predicting the winner by comparing winning percentage at the time of the match
print(correct/predictions[predictions["actual"] != 2].shape[0])

0.5455491514569324

In [34]:
df.groupby("home").apply(lambda x:x[x["won"] == 1].shape[0]/x.shape[0])

home
0.0    0.428314
1.0    0.571686
dtype: float64

In [35]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [36]:
#To create a better model, we have to stress multiple factors even more:
#home/away game
#team record (since NBA teams roster/strength change quite frequently, we'll use the winning percentage in last 25 games)
#Using this improved model, we can see if there are any changes to the accuracy
def find_team_averages(team):
    return team.rolling(25).mean()

def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys = False).apply(lambda x:shift_col(x, col_name))

df_rolling = df_rolling.groupby(["team","season"], group_keys = False).apply(find_team_averages)

rolling_cols = [f"{col}_new" for col in df_rolling.columns]

df_rolling.columns = rolling_cols

df = (pd.concat([df, df_rolling], axis = 1)).dropna()

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")
full = df.merge(df[rolling_cols + ["team_opp_next","date_next", "team"]],left_on=["team", "date_next"],right_on = ["team_opp_next", "date_next"])
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

selected_columns = full.columns[~full.columns.isin(removed_columns)]
sfs.fit(full[selected_columns], full["target"])
predictors = list(selected_columns[sfs.get_support()])
predictions = backtest(full, rr, predictors)

accuracy_score(predictions["actual"], predictions["prediction"])
#Our Accuracy results in 65.2%, a much more improved result than before.

0.6528409090909091